### PR TITLE
Add pathtobundle and cacrts

### PR DESCRIPTION
**Pull request by alexisdondon**
Adding pathToCaBundle and cacerts as string.
Remove crts as array.

I have deprecated crts in region on the api and will propose a PR to delete this field in the next versions of api.

### CODE REVIEW

**Comment by garronej** [comment]
You are missing the actual injection that has to be done in  `src/core/usecases/launcher.ts`

**Comment by garronej** [comment]
If it's not ready for review please convert to draft until it is.

**Comment by olevitt** [comment]
> You are missing the actual injection that has to be done in `src/core/usecases/launcher.ts`

I think it's already present in the codebase as this PR only changes the structure of `certificateAuthorityInjection` (renaming `crts` to `cacerts` and adding `pathToCaBundle`) but does not add any new top-level key. So my understanding is that `src/core/usecases/launcher.ts` does not have to be changed for that. Can you doublecheck ?

**Comment by garronej** [comment]
@olevitt you're right, my bad.

**Comment by garronej** [comment]
> If it's not ready for review please convert to draft until it is.  

@alexisdondon sorry about that! 😕

**Pull request merged**
