### PR TITLE
Minor English typo fix

### PR DESCRIPTION
**Pull request by qgau**

### CODE REVIEW

**Comment by odysseu** [comment]
I disagree on translation;
It is a catalog of multiple service**s**

**Comment by qgau** [comment]
Hello,

Thank you for your feedbacks.

I believe we are talking about _attributives nouns_ here.
Because here, precisely as you said, "services", plurial, just means several services, and not a specific and different meaning, "service catalog" should be used to describe a catalog of services.

More resources and examples:
- https://en.wikipedia.org/wiki/Noun_adjunct
- https://ell.stackexchange.com/questions/24200/how-do-you-use-plural-or-singular-form-of-an-adjective
- deepl.com/ will output "service catalog" if you try a translation (for example, from French "catalogue de services")

That being said, English is not my native language, so I would follow an Expert point of view.
That is your call, and this PR is just a proposal ;-)

Cheers!

**Comment by mmwinther** [comment]
@qgau is correct, it should be "service catalog" (I'm a native English speaker)

**Comment by garronej** [comment]
Sorry, there was a big refactoring going on so I couldn't merge but I applyed the fix manually.  
Thanks a lot!

**Pull request closed without merging**
