### PR TITLE
Helm chart: Own service accounts for API and Web 

### PR DESCRIPTION
**Pull request by johnksv**
See issue #616 which this PR resolves.

Question: Where should i update the doc (as this is a breaking change)? 

PS: I have not had the opportunity to test this yet, but wanted to create the PR such that it can be discussed.

### Commit message describing the change:

Service account was previously specified at root level. When using serviceAccount.create, this was OK, since api and web would then get their own SAs. When serviceAccount.create was false however, the same SA would be used for both api and web, which is very problematic of several reasons.

This commit fix this issue by moving the serviceAccount field from root to both api and web. This also make it clearer what happen under-the-hood.
The change is breaking, and major version is therefore bumped.

### CODE REVIEW

**Comment by olevitt** [comment]
LGTM (tested on our setup) except the fact that I think you should not bump the helm chart version manually as it's handled by the CI but maybe @garronej can enlighten us on this ?  
@johnksv could you enable "allow commits from maintainers" from your PR so that we can adjust it (e.g rebase / remove the helm version bump) before merging ?

**Comment by johnksv** [comment]
Thanks, @olevitt . Rebased on main now and reverted bump of chart version.
Looks like "allow commits from maintainers" is not an option. Hm, maybe that is because of some settings on the fork.

**Comment by garronej** [comment]
@johnksv Thanks a lot for this PR!   

> I think you should not bump the helm chart version manually as it's handled by the CI but maybe @garronej can enlighten us on this ?

@olevitt @johnksv, You did good by bumping the Helm chart version to the next major. The deployment workflow automatically bump the chart when there is a bump on either -web or -api but you can also pub the helm chart version manually, this too will triger a release.  
Beside, our workflow isn't smart to the point of being able to figure out if the update constitute a breaking change or not.  

Regarding the update of the docs.onyxia.sh website, there's two approach.  
- You can submit a PR here: https://github.com/InseeFrLab/docs.onyxia.sh/blob/main/migration-guides/v5-greater-than-v6.md  
- Or you can use the GitBook.com "What you see is what you get" User interface, I've sent you an invite on your ssb.no address. Be sure to update the v6 version of the doc.  

image


Thanks again for your contribution.

**Comment by johnksv** [comment]
OK, I'll bump the chart version again, and write some doc (got your invitation)

**Comment by johnksv** [comment]
Added a "change request" in gitbook, @garronej . Feel free to edit the docs (and this PR of course) accordingly

**Comment by garronej** [comment]
Sorry for the delay, I'll fix the conflict and merge asap

**Pull request merged**
